### ISSUE TITLE
am bagat utilizator !@#$%^&*()_+=-0987654321~`{}|[]\:";'<>?,./

### ISSUE THREAD

**Issue by M4rYu5** [sorryb/Northwind#155]
dar a busit ceva si in baza de date nu mai apare bine

**Comment by M4rYu5** [comment]
le baga in baza de date corect (presupun), dar la afisare nu mai stie.
Sugestie: Creare dictionar de caractere alphanumerice + caractere speciale pentru toate campurile din sing up (posibil si la adaugare produse, utilizatori, ....)
note: #numele la manage user nu vezi numele

**Comment by Iamsdl** [comment]
e din cauza ca un in username ai si ". trebuie inlocuite in cshtml-uri cu &quot; daca sunt folosite in interiorul atributelor.

**Comment by Iamsdl** [comment]
Am rezolvat-o. am pus html encoding la inceput in controller. Eu zic #153  sa nu o rezolvam. Poate sa ii punem mesaj de eroare customizat.
