### ISSUE TITLE
In cazul in care introducem asta logeazao eroare si da refresh la pagia

### ISSUE THREAD

**Issue by CosminSA** [sorryb/Northwind#169]
![image](https://user-images.githubusercontent.com/30923290/30692205-2b854c70-9ed3-11e7-8341-492f0b7cceca.png)
Macar sa dea mesaj

**Comment by CosminSA** [comment]
![image](https://user-images.githubusercontent.com/30923290/30692363-e8036274-9ed3-11e7-9075-c9679684eb61.png)
si de asemeni poate fi creat dau nu poate fi modificat

**Comment by Iamsdl** [comment]
se modifica, dar nu da redirect
