### ISSUE TITLE
eroare in lista de comenzi !

### ISSUE THREAD

**Issue by nchmona** [sorryb/Northwind#170]
![b5b79ae2-ae55-47f6-8212-541ff10c0a83](https://user-images.githubusercontent.com/31092199/30694460-c4cde00a-9edc-11e7-827d-0ab33cd0ee79.png)

**Comment by Iamsdl** [comment]
e din cauza ca are un produs cu nume null

**Comment by M4rYu5** [comment]
gata, acum nu ar mai trebui sa existe nici o modalitate prin care numele unui produs sa devina null
*am modificat campul in required (atat server cat si client)
**server am adaugat langa validare model un && nume != null
