### ISSUE TITLE
Daca stocul este 0 produsul nu devine indisponibil. De asemenea "srtoc"

### ISSUE THREAD

**Issue by Iamsdl** [sorryb/Northwind#175]
![image](https://user-images.githubusercontent.com/20208940/30699265-e69e8206-9eec-11e7-98cd-71daf9054bcb.png)

**Comment by M4rYu5** [comment]
partea cu srtoc rezolvata 🔪

**Comment by M4rYu5** [comment]
daca cantitatea din stoc (in produse) este <= 0  atunci produsul va deveni indisponibil

**Comment by PAndreea** [comment]
toate serviciile in stoc sunt 0 dar nu sunt indisponibile

**Comment by M4rYu5** [comment]
serviciile nu mai sunt decrementate
