### ISSUE TITLE
Probleme la link-uri si butoane in pagina

### ISSUE THREAD

**Issue by nchmona** [sorryb/Northwind#37]
In entitatile: Servicii,Comenzi, Clienti, Angajati,Furnizori , Expeditori apare search-ul de 2x in pagina si trebuie sters unul dintre el .Model de Search in  pagina gasiti in Regiune sau Categorii.

In toate entitatile trebuie sa avem butoane in loc de link pe ''Modifica","Inapoi la lista","Inapoi","Adauga" si "Sterge".

Din Comenzi->Detalii Comanda trebuie sters link-ul  "Inapoi la lista"(deoarece apare de 2x pe pagina).
Aceeasi situatie se regaseste si in entitatea Regiuni->Teritorii.
Este posibil sa fie la fel si in categoria Servicii, nu va pot spune concret pt ca nu mi se incarca pagina.

**Comment by Iamsdl** [comment]
comenzi->detalii->modifica
inapoi la lista e link nu buton

**Comment by Iamsdl** [comment]
mai e un link in furnizori->modifica
