### ISSUE TITLE
Trebuie curatat web.config si fisierul de proiect prj)

### ISSUE THREAD

**Issue by sorryb** [sorryb/Northwind#56]
- de scos fisierul aspx cu ReportView-er
- de curatat web.config

**Comment by Iamsdl** [comment]
am sters din packages, verifica daca mai sunt chestii in plus. la mine nu mai sunt

**Comment by sorryb** [comment]
De scos key-le de la JSon-uri.

**Comment by Iamsdl** [comment]
gata web.config
mam uitat in history si fata de start tot ce avem in plus acum sunt 3 chestii de la identity, log4net si appsettings report server.

**Comment by M4rYu5** [comment]
cred ca se poate inchide acest bug
