### ISSUE TITLE
ChangeUser trebuie facut si pentru DAshbord layout

### ISSUE THREAD

**Issue by sorryb** [sorryb/Northwind#58]
La utilizatori trebuie sa aiba layout diferit in Administrare.

**Comment by sorryb** [comment]
Deci ChangeUser este folosit doar in administrare(Dashboard)...pe el trebuie sa fie doar dashboar layout.
Insa Register se pare ca este utilizat in ambele locuri...Acest view trebuie sa fie de doau ori:
- Register
-RegisterAdmin

**Comment by CosminSA** [comment]
Facut
