### ISSUE TITLE
Sa apara poze la Utilizatori - in Index pe Administrare(Dashboard)

### ISSUE THREAD

**Issue by sorryb** [sorryb/Northwind#65]
In coloana de Utilizatori sa apara si poza lor...la fel in Detaliu.
Sa existe functionalitatea si la Adaugare User- sa se poata adauga si Utilizator.

**Comment by nchmona** [comment]
In momentul in care incarcam poza in utilizatori si ii dam salvare ne intoarce la pagina principala. Corect este sa ramanem pe aceeasi pagina (de utilizatori) singura modificare fiind aparitia pozei incarcate.
