### ISSUE TITLE
Adaugare erori in EventView-er folosind log4Net

### ISSUE THREAD

**Issue by sorryb** [sorryb/Northwind#67]
Am configurat aplicatia sa logheze erorile in Event View-er (in cmd rulati eventvwr) unde le vedeti in NorthwindLog in' Application and Services Log'.

In controller trebuie sa adaugati un singur try-catch(vezi HomeController) in fiecare metoda astfel 👍 
 private log4net.ILog logger = log4net.LogManager.GetLogger(typeof(HomeController));      
public ActionResult ...()
        {
            try
            {
                 ...
                 ...

                return ...
            }
            catch (Exception exception)
            {
                logger.Error(exception.ToString());
                return View();
            }
        }

**Comment by nchmona** [comment]
in account trebuie adaugat logger
