### ISSUE TITLE
Vanzari pe ani -Dashboard

### ISSUE THREAD

**Issue by nchmona** [sorryb/Northwind#77]
Trebuie modificat in diagrama perioada anilor . In loc de perioada 1996-01->1997-01 sa apara 2017-06->2017-09.

**Comment by sorryb** [comment]
Cosmine...sa scoti tu de acolo , din Dashboard adaugarle de ani si verificari genul 
        if(Convert.ToDateTime(itemSalesByYear.OrderDate).Year<=1998)
                    { 
                    if (int.Parse(itemDashboardMorrisBarData.Year) == Convert.ToDateTime(itemSalesByYear.OrderDate).Year+19)

Am modificat eu in Initializer 1996 in 2016 si 1997 in 2017 ; Ca sa para datele cat mia reale si apropiate de zilele noastre !!!
