### ISSUE TITLE
La conectarea la serverul de Reporting Services, userul si parola trebuie luate din connection string

### ISSUE THREAD

**Issue by sorryb** [sorryb/Northwind#90]
Nu e bine sa apara in clar !

**Comment by sorryb** [comment]
eventual sa fie cerute de Browser !

**Comment by Iamsdl** [comment]
Nu prea stiu cum sa fac. O idee ar fi sa mai fac un view cu un form de login, dar dupa mai cere odata login si cand se da click prima data pe unul din rapoarte si e cam enervant.
